timeout: 300 # seconds
marker_radius: 0.2 # meters
markers:
  # - [ 0, 0, 15 ]
  - [ 1, 0, 15 ]
  - [ 2, 0, 15 ]
  - [ 3, 0, 15 ]
  - [ 4, 0, 15 ]
  - [ 5, 0, 15 ]
  - [ 6, 0, 15 ]
  - [ 7, 0, 15 ]
  - [ 8, 0, 15 ]
  - [ 9, 0, 15 ]
  - [ 10, 0, 15 ]
  - [ 10, 1, 15 ]
  - [ 10, 2, 15 ]
  - [ 10, 3, 15 ]
  - [ 10, 4, 15 ]
  - [ 10, 5, 15 ]
  - [ 10, 6, 15 ]
  - [ 10, 7, 15 ]
  - [ 10, 8, 15 ]
  - [ 10, 9, 15 ]
  - [ 10, 10, 15 ]
